---

- name: CIS 5.1.2 | test for existence /etc/crontab
  stat:
    path: /etc/crontab
  register: file_exists

- name: CIS 5.1.2 | ensure permission 0700 on /etc/cron.d/
  file:
    path: /etc/crontab
    mode: 0600
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 5.1.3 | test for existence /etc/cron.hourly
  stat:
    path: /etc/cron.hourly
  register: file_exists

- name: CIS 5.1.3 | ensure permission 0700 on /etc/hourly
  file:
    path: /etc/cron.hourly
    mode: 0700
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 5.1.4 | test for existence /etc/cron.daily
  stat:
    path: /etc/cron.daily
  register: file_exists

- name: CIS 5.1.4 | ensure permission 0700 on /etc/cron.daily
  file:
    path: /etc/cron.daily
    mode: 0700
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 5.1.5 | test for existence /etc/cron.weekly
  stat:
    path: /etc/cron.weekly
  register: file_exists

- name: CIS 5.1.5 | ensure permission 0700 on /etc/cron.weekly
  file:
    path: /etc/cron.weekly
    mode: 0700
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 5.1.6 | test for existence /etc/cron.monthly
  stat:
    path: /etc/cron.monthly
  register: file_exists

- name: CIS 5.1.6 | ensure permission 0700 on /etc/cron.monthly
  file:
    path: /etc/cron.monthly
    mode: 0700
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 5.1.7 | test for existence /etc/cron.d
  stat:
    path: /etc/cron.d
  register: file_exists

- name: CIS 5.1.7 | ensure permission 0700 on /etc/cron.d
  file:
    path: /etc/cron.d
    mode: 0700
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists
